version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst neko --version 2.3.0 -y
  - cinst haxe --version 4.1.5 -y
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  # Install project dependencies
  - haxelib install lime 7.9.0
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel
  - haxelib run lime setup
  - haxelib install flixel-tools
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib git flixel-studio https://github.com/Dovyski/flixel-studio.git
  - haxelib install hscript
  - haxelib install newgrounds
  - haxelib install flixel-addons
  - haxelib git systools https://github.com/polybiusproxy/systools.git
  - haxelib git polymod https://github.com/larsiusprime/polymod.git funkinfixes
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib list

build_script:
  - haxelib run lime rebuild systools windows
  - haxelib run lime build windows

artifacts:
  - path: export/release/windows/bin
    name: WindowsBuild
    type: zip
